---
name: Build/push Image to GCP AR
on:
  pull_request:
    branches: 
      - main

env:
  IMAGE_NAME: app
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GIT_TAG: 1.0.0

jobs:
  Build-And-Push-Image:
    name: Build Image 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.ACCESS_KEY }}


    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:${{ env.GIT_TAG }} .

    # - name: Automatic Tagging of Releases
    #   id: increment-git-tag
    #   run: |
    #     bash ./scripts/git_update.sh -v major 


    - name: Configure Docker Client
      run: | 
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker  northamerica-northeast2-docker.pkg.dev --quiet

    # - name: Push Docker Image to Container Registry (GCR)
    #   # env:
    #   #   GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }} ${{ github.event.pull_request.number }}
    #   run: |
    #     docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
    #     docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ env.GIT_TAG }}
    #     docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
    #     docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ env.GIT_TAG }}


    - name: Push Docker Image to Artifact Registry
      # env:
      #   GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        docker images
        docker tag $IMAGE_NAME:${{ env.GIT_TAG }} northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:${{ env.GIT_TAG }} northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:${{ env.GIT_TAG }}
        docker push $IMAGE_NAME:${{ env.GIT_TAG }}

