---
name: Build/push Image to GCR
on:
  push:
    branches: 
      - main

env:
  IMAGE_NAME: app
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  Build-Image:
    name: Build Image 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.ACCESS_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    # - name: Automatic Tagging of Releases
    #   id: increment-git-tag
    #   run: |
    #     bash ./scripts/git_update.sh -v major

  Push-Image-GCR: 
    name: Push Image To GCR
    runs-on: ubuntu-latest
    needs: Build-Image
    steps: 
    - name: Configure Docker Client
      run: | 
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker  northamerica-northeast2-docker.pkg.dev --quiet

    - name: Push Docker Image to Container Registry (GCR)
      # env:
      #   GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.event.pull_request.number }}
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.event.pull_request.number }}

  Push-Image-AR: 
    name: Push Image To GCR
    runs-on: ubuntu-latest
    needs: Push-Image-GCR
    steps:
    - name: Push Docker Image to Artifact Registry
      # env:
      #   GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        docker tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:${{ github.event.pull_request.number }}
        northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/dhakshina-nine/$IMAGE_NAME:${{ github.event.pull_request.number }}
