---
name: Build/push Image AR/ Deploy to GKE
on:
  pull_request:
    branches: 
      - main

env:
  IMAGE_NAME: app
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GIT_TAG: 1.0.0
  GKE_CLUSTER: autopilot-cluster-9   
  GKE_ZONE: northamerica-northeast2-b 
  DEPLOYMENT_NAME: app-deploy
  IMAGE: app

jobs:
  Build-And-Push-Image:
    name: Build Image 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.ACCESS_KEY }}


    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:${{ github.sha }} .

    # - name: Automatic Tagging of Releases
    #   id: increment-git-tag
    #   run: |
    #     bash ./scripts/git_update.sh -v major 


    - name: Configure Docker Client
      run: |
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker  northamerica-northeast2-docker.pkg.dev --quiet

    - name: Push Docker Image to Container Registry (GCR)
      run: |
        docker tag $IMAGE_NAME:${{ github.sha }} gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }}
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }}


    - name: Push Docker Image to Artifact Registry
      run: |
        docker images
        docker image tag $IMAGE_NAME:${{ github.sha }}  northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/dhakshina-nine/$IMAGE_NAME:${{ github.sha }}
        docker push northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/dhakshina-nine/$IMAGE_NAME:${{ github.sha }}


    - name: Deploy
      run: |
        sed -i -e 's/GITHUB_SHA/'"$GITHUB_SHA"'/' ${{ github.workspace }}/.github/manifests/deployment.yaml
        kubectl apply -f ${{ github.workspace }}/.github/manifests/deployment.yaml